spring:
  datasource:
    url: jdbc:h2:mem:apisrestdb

azure:
  maps:
    base:
      uri: https://atlas.microsoft.com
    api:
      key: ${AZURE_MAPS_KEY}

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${CERTIFICATE_PASSWORD}
    key-store-type: PKCS12
    key-alias: apis-rest

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10