version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn verify
      - coverage-reporter/send_report:
          coverage-reports: 'target/site/jacoco/jacoco.xml'
          skip: false

workflows:
  build:
    jobs:
      - build-and-test

orbs:
  coverage-reporter: codacy/coverage-reporter@13.5.2