version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: ./mvnw -B -DskipTests clean package
      - run:
          name: Unit tests
          command: ./mvnw test -DskipITs -Dspring.profiles.active=test
      - run:
          name: Integration tests
          command: ./mvnw failsafe:integration-test failsafe:verify -Dspring.profiles.active=test
      - run:
          name: JaCoCo report
          command: ./mvnw jacoco:report
      - coverage-reporter/send_report:
          coverage-reports: 'target/site/jacoco/jacoco.xml'
          skip: false

workflows:
  build:
    jobs:
      - build-and-test

orbs:
  coverage-reporter: codacy/coverage-reporter@13.5.2